-- Schema para Catequese Desktop
create extension if not exists "pgcrypto";

create table if not exists paroquias (
  id uuid primary key default gen_random_uuid(),
  nome text not null unique
);

create table if not exists escolas (
  id uuid primary key default gen_random_uuid(),
  nome text not null unique
);

create table if not exists catequistas (
  id uuid primary key default gen_random_uuid(),
  nome text not null unique
);

create table if not exists centros_catequese (
  id uuid primary key default gen_random_uuid(),
  nome text not null unique,
  paroquia_id uuid references paroquias(id)
);

create table if not exists alunos (
  id uuid primary key default gen_random_uuid(),
  nr_matricula integer generated by default as identity,
  ano_matricula integer not null,
  paroquia_id uuid references paroquias(id),
  escola_id uuid references escolas(id),
  centro_id uuid references centros_catequese(id),
  catequista_id uuid references catequistas(id),
  nome_aluno text not null,
  nome_pai text,
  nome_mae text,
  data_nascimento date,
  naturalidade text,
  batizado boolean default false,
  data_batismo date,
  lugar_batismo text,
  encarregado_nome text,
  morada text,
  localidade text,
  codigo_postal text,
  telemovel text,
  email text,
  ano_catecismo integer,
  ano_escolar integer,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists alunos_ano_idx on alunos(ano_matricula);
create index if not exists alunos_catequista_idx on alunos(catequista_id);
create index if not exists alunos_centro_idx on alunos(centro_id);

create table if not exists presencas_mensais (
  id uuid primary key default gen_random_uuid(),
  aluno_id uuid not null references alunos(id) on delete cascade,
  ano_matricula integer not null,
  catequista_id uuid references catequistas(id),
  ano_catecismo integer,
  out boolean default false,
  nov boolean default false,
  dez boolean default false,
  jan boolean default false,
  fev boolean default false,
  mar boolean default false,
  abr boolean default false,
  mai boolean default false,
  jun boolean default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'presencas_mensais_unique') then
    alter table presencas_mensais
      add constraint presencas_mensais_unique
      unique (aluno_id, ano_matricula, catequista_id, ano_catecismo);
  end if;
end $$;

create index if not exists presencas_mensais_filter_idx
  on presencas_mensais(catequista_id, ano_matricula, ano_catecismo);

alter table paroquias enable row level security;
alter table escolas enable row level security;
alter table catequistas enable row level security;
alter table centros_catequese enable row level security;
alter table alunos enable row level security;
alter table presencas_mensais enable row level security;

create policy "authenticated_select" on paroquias for select to authenticated using (true);
create policy "authenticated_insert" on paroquias for insert to authenticated with check (true);
create policy "authenticated_update" on paroquias for update to authenticated using (true);
create policy "authenticated_delete" on paroquias for delete to authenticated using (true);

create policy "authenticated_select" on escolas for select to authenticated using (true);
create policy "authenticated_insert" on escolas for insert to authenticated with check (true);
create policy "authenticated_update" on escolas for update to authenticated using (true);
create policy "authenticated_delete" on escolas for delete to authenticated using (true);

create policy "authenticated_select" on catequistas for select to authenticated using (true);
create policy "authenticated_insert" on catequistas for insert to authenticated with check (true);
create policy "authenticated_update" on catequistas for update to authenticated using (true);
create policy "authenticated_delete" on catequistas for delete to authenticated using (true);

create policy "authenticated_select" on centros_catequese for select to authenticated using (true);
create policy "authenticated_insert" on centros_catequese for insert to authenticated with check (true);
create policy "authenticated_update" on centros_catequese for update to authenticated using (true);
create policy "authenticated_delete" on centros_catequese for delete to authenticated using (true);

create policy "authenticated_select" on alunos for select to authenticated using (true);
create policy "authenticated_insert" on alunos for insert to authenticated with check (true);
create policy "authenticated_update" on alunos for update to authenticated using (true);
create policy "authenticated_delete" on alunos for delete to authenticated using (true);

create policy "authenticated_select" on presencas_mensais for select to authenticated using (true);
create policy "authenticated_insert" on presencas_mensais for insert to authenticated with check (true);
create policy "authenticated_update" on presencas_mensais for update to authenticated using (true);
create policy "authenticated_delete" on presencas_mensais for delete to authenticated using (true);

do $$
begin
  if not exists (
    select 1 from pg_publication_tables where pubname = 'supabase_realtime' and tablename = 'alunos'
  ) then
    alter publication supabase_realtime add table alunos;
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_publication_tables where pubname = 'supabase_realtime' and tablename = 'presencas_mensais'
  ) then
    alter publication supabase_realtime add table presencas_mensais;
  end if;
end $$;
